//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guardian
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresse
    {
        public int Id { get; set; }
        public string pays { get; set; }
        public string ville { get; set; }
        public string quartier { get; set; }
        public double latitude { get; set; }
        public double longitude { get; set; }
        public Nullable<double> altitude { get; set; }
        public string precision { get; set; }
        public int CRIMINELId_crim { get; set; }
    
        public virtual CRIMINEL CRIMINEL { get; set; }
    }
}
