//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guardian
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRIMINEL
    {
        public CRIMINEL()
        {
            this.DELIT = new HashSet<DELIT>();
            this.Adresse = new HashSet<Adresse>();
        }
    
        public int Id_crim { get; set; }
        public string matricul_crim { get; set; }
        public string nom_crim { get; set; }
        public string prenom_crim { get; set; }
        public System.DateTime datenaiss_crim { get; set; }
        public string typ_piece { get; set; }
        public string num_piece { get; set; }
        public string crim_nationa { get; set; }
        public string crim_profes { get; set; }
        public System.DateTime date_enreg { get; set; }
        public byte[] photo_crim { get; set; }
        public Nullable<bool> deffere { get; set; }
        public Nullable<decimal> crim_taill { get; set; }
        public Nullable<decimal> crim_poid { get; set; }
        public string contatct_crim { get; set; }
    
        public virtual ICollection<DELIT> DELIT { get; set; }
        public virtual ICollection<Adresse> Adresse { get; set; }
    }
}
