//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guardian
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELIT
    {
        public int Id_delit { get; set; }
        public string nom_delit { get; set; }
        public int CRIMINELId_crim { get; set; }
        public string lieu_delit { get; set; }
    
        public virtual CRIMINEL CRIMINEL { get; set; }
    }
}
