//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guardian
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTS
    {
        public int Id_doc { get; set; }
        public byte[] doc { get; set; }
        public int PLAINTEId_aff { get; set; }
        public string docname { get; set; }
    
        public virtual PLAINTE PLAINTE { get; set; }
    }
}
