//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guardian
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GuardianEntities1 : DbContext
    {
        public GuardianEntities1()
            : base("name=GuardianEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CRIMINEL> CRIMINEL { get; set; }
        public virtual DbSet<DELIT> DELIT { get; set; }
        public virtual DbSet<DOCUMENTS> DOCUMENTS { get; set; }
        public virtual DbSet<LOG> LOG { get; set; }
        public virtual DbSet<PLAIGNANT> PLAIGNANT { get; set; }
        public virtual DbSet<PLAINTE> PLAINTE { get; set; }
        public virtual DbSet<USER> USER { get; set; }
        public virtual DbSet<Adresse> AdresseSet { get; set; }
    }
}
