//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guardian
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG
    {
        public int Id { get; set; }
        public string identifiant_log { get; set; }
        public string nom_log { get; set; }
        public string grade { get; set; }
        public System.DateTime date_log { get; set; }
        public byte[] user_photo { get; set; }
    }
}
