//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guardian
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAIGNANT
    {
        public PLAIGNANT()
        {
            this.PLAINTE = new HashSet<PLAINTE>();
        }
    
        public int Id_plaignant { get; set; }
        public string nom_plai { get; set; }
        public string prenom_plai { get; set; }
        public string contact_plai { get; set; }
        public string adress_plai { get; set; }
        public string professi_plai { get; set; }
    
        public virtual ICollection<PLAINTE> PLAINTE { get; set; }
    }
}
