//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guardian
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAINTE
    {
        public PLAINTE()
        {
            this.DOCUMENTS = new HashSet<DOCUMENTS>();
        }
    
        public int Id_aff { get; set; }
        public string descrip_aff { get; set; }
        public string cause_aff { get; set; }
        public string professconvo { get; set; }
        public string nom_convoc { get; set; }
        public int PLAIGNANTId_plaignant { get; set; }
        public string code_aff { get; set; }
        public System.DateTime date_aff { get; set; }
        public Nullable<bool> classe { get; set; }
    
        public virtual PLAIGNANT PLAIGNANT { get; set; }
        public virtual ICollection<DOCUMENTS> DOCUMENTS { get; set; }
    }
}
