//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guardian
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public int id_user { get; set; }
        public string nom_user { get; set; }
        public string prenom_user { get; set; }
        public System.DateTime dob_user { get; set; }
        public string mail_user { get; set; }
        public string contact { get; set; }
        public string grade_user { get; set; }
        public string identifiant_user { get; set; }
        public string psswrd_user { get; set; }
        public byte[] photo_user { get; set; }
        public bool actif { get; set; }
        public string profil { get; set; }
    }
}
